discord/lilliput

opencv.cpp, opencv.go, opencv.hpp
output format should never exceed 8 bits/channel. some output types
can't handle this, and our internal assumptions require this anyway.
=> dont exceed 8 bits/channel

avcodec.cpp
32-byte may be able to use more simd primitives, but apparently it
causes distortion in some videos. we may even want to drop down to 1 if
we find other buggy videos
=> use 16-byte alignment for av_image_fill_arrays

avcodec.cpp, opencv.cpp, opencv.hpp
libavcodec doesnt really work if the stride isn't a multiple of 32. but
thankfully opencv supports arbitrary inter-row strides, so just take
advantage of that.
=> use stride of multiple of 32 in resize target

lilliput.go, opencv.go
The current code produces the following error on an empty buffer. The added range check prevents it from panicking, instead returning an error.
```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/discordapp/lilliput.newOpenCVDecoder(0xc4200e6200, 0x0, 0x200, 0x0, 0x0, 0xc420130040)
/home/alexrsagen/go/src/github.com/discordapp/lilliput/opencv.go:234 +0x16a
github.com/discordapp/lilliput.NewDecoder(0xc4200e6200, 0x0, 0x200, 0x0, 0x200, 0x0, 0x0)
/home/alexrsagen/go/src/github.com/discordapp/lilliput/lilliput.go:67 +0x72
```
=> Add range check to NewDecoder

giflib.cpp
The GIF spec is fun and allows the GIF itself to define a canvas/viewport size, and then each frame can define its own size. Frames can also define a starting coordinate, so for example a 400x400 gif might have a 30x20 frame that starts at (180, 100).
I took a lazy approach to these partial frames. Rather than trying to figure out how to rescale the coordinates, e.g. what is 99% of (180, 100), I decided to just composite the new frame on top of the previous frame and then use standard resizing for the composited frame. In the encoder, we consider which color from the palette to use. The right color could be a transparency color if the color at (x, y) is close to the color at (x, y) in the previous frame. And so my intention was that we would turn these partial frames into full frames with …
=> on partial frame, allocate a transparency color

giflib.cpp
for some odd reason, images can have multiple GCB extension blocks per frame. this switches us to use the last block instead of the first, which seems to be how gif renderers generally work.
=> respect last gcb, not first

opencv.go, opencv_test.go
- Add unit test for APNG detection
- Split out utility for walking PNG chunks as some kind of "iterator"
- Add unit tests for that and for detecting the content length of PNG
Test with `go test`
Next, will add similar thing for jpeg EOI
=> [lilliput] Support detecting early IEND in PNG files

examples/main.go, opencv.go, opencv_test.go
Walk jpeg segments to find EOI and report content length accurately Sadly this seems to require a linear scan of most of the content
a jpeg file consists of a sequence of segments
- segments are delimited by 0xFF, then a single non-zero byte for type. but ECS segment is not delimited by 0xFF
- EOI segment type is is 0xD9 while SOI is 0xD8
- most segments have 2 bytes for size following the type, but not the actual image data in entropy coded segments (ECS)
- in ECS, 0xFF may occur naturally and is marked as data instead of a new segment by adding 0x00 immediately after the 0xFF
Add a couple unit tests for jpeg data
- https://github.com/corkami/formats/blob/master/image/jpeg.md
- https://en.wikipedia.org/wiki/JPEG#Syntax_and_structure
=> [lilliput] Add jpeg content length detection

avcodec.go, giflib.go
Didn't notice these others existed and would default to 0. Let's set real values.
=> Set contentLength field in all ImageHeaders

avcodec.cpp
This fixes a bug introduced in #146 where the `cvMat->cols` should be `stepSize`. Led to some funky transformations like:
Co-authored with @rcombs
=> Fix reference to stepsize in call to av_image_fill_linesizes.

examples/main.go, lilliput.go, ops.go
this adds the ability to define a (weak) upper bound on ongoing work. while it would be better to reject/limit the request up front based on some heuristics, this acts as a catch-all which can be tuned on the fly for general sanity and incident response
=> Add timeout option for video/gif encoding

avcodec.go, giflib.go, lilliput.go, opencv.go, webp.cpp, webp.go, webp.hpp
Rather than call opencv to get libwebp, call libwebp directly. We can make this wrapper pretty easily because libwebp has a nice modern API without a lot of edge cases.
=> webp wrapper

lilliput.go, lilliput_test.go
Fixed WebP image detection to prevent misidentification of WAV audio files by checking both the `RIFF` and `WEBP` markers in the file header. WAV and WebP use the same container (denoted by `RIFF`), but have different file formats (denoted by the later bytes `WEBP` and `WAV`). Added unit tests to verify correctness.
[WebP Container Specification](https://developers.google.com/speed/webp/docs/riff_container#webp_file_header)
```
→ hexdump -C tos-intro-3s.wav | head
00000000  52 49 46 46 8a 13 08 00  57 41 56 45 66 6d 74 20  |RIFF....WAVEfmt |
00000010  10 00 00 00 01 00 02 00  44 ac 00 00 10 b1 02 00  |........D.......|
00000020  04 00 10 00 4c 49 53 54  1a 00 00 00 49 4e 46 4f  |....LIST....INFO|
00000030  49 53 46 54 0e 00 00 00  4c 61 76 66 36 30 2e 31  |ISFT....Lavf60.1|
00000040  36 …
```
=> Fix WebP image detection

avcodec.cpp, avcodec.go, avcodec.hpp
This PR gates HEVC/H.265 decoder support behind a build flag for now. It can be enabled by passing the following to the go cmd: `-ldflags=-X=github.com/discord/lilliput.hevcEnabled=true`
=> [hevc] gate HEVC/h.265 decoder behind build flag

avcodec.cpp
Expands the reported resolution as needed to produce a non-anamorphic output image, both for metadata and thumbnails.
This works for files that have a sample aspect ratio tagged at the container level.
=> avcodec: improve support for anamorphic video

opencv.cpp
Fixes the handling of source images that include an alpha channel when encoding to a format that does not support alpha channels (i.e. JPEG). Previously the output image was rendered incorrectly, not using a substitute background color when an alpha channel was present in the source.
With this change, Lilliput will recognize that a alpha channel is present, create a white background mat, and overlay the BGR channels of the source image onto the white background.
=> Fix handling of alpha channels in image encoding.

lilliput.go, opencv.cpp, opencv.go, opencv.hpp
Builds on #169 
Ensure that alpha channel is preserved when encoding to a format that supports it, such as PNG.
=> Preserve alpha channel when encoding to PNG.

lilliput_test.go
Fixes the unit test expectations for the width of anamorphic video inputs. The expected values changed as a result of #165 .
=> Fix unit test expectations for width of anamorphic video input.

lilliput.go, opencv.cpp, opencv.go, opencv.hpp
Reverting changes related to the merging of BGR channels onto an alpha channel when outputting to a format that doesn't support alpha channels. This introduced a regression when creating a BGR output (i.e. JPEG) from a video input file. The video input frame is represented as BGRA, even though only the BGR channels are used. This led to distorted outputs, as merging was incorrectly applied.
=> Revert changes for handling of alpha channels.

webp.cpp, webp_test.go
This commit fixes a regression introduced in #178 that incorrectly used frame-level details for canvas size and alpha channels. The fix ensures that we use information from the WebP container instead.
Adds a test-case for generation of a single-frame output from an animated WebP input. Prior to this fix, this test case would output a single frame consisting of only the background color since the presence of an alpha channel was inferred from the first frame rather than the container flag.
=> fix: Use WebP container info for canvas size and alpha channel

ops.go
This PR modifies both the `fit` and `resize` functions to handle dimensions more consistently, with `fit` using a new calculation method and `resize` simplifying to always use the exact requested dimensions. This behavior regressed with the changes #178 , which this PR restores.
- Introduced `calculateExpectedSize` helper function used by the `fit` function.
- Updated `fit` function to use this new helper function.
- Simplified `resize` function to always use exact output dimensions.
- Added `min` helper function for dimension comparisons.
1. Fit function (new logic):
a. Both dimensions smaller than source:
Original: 800x600, Requested: 400x300
Result: 400x300 (scales down, maintaining aspect ratio, may crop)
b. Square fit larger than original:
Original: 800x600, Requested: 1000x1000 …
=> fix: Improve fit and resize functions to handle dimensions consistently.

webp.cpp, webp_test.go
Fixes a bug where a call was made to `WebPDataClear(&icc_data)` using externally owned ICC color profile data, potentially causing a panic. This call is unnecessary since the `icc_data` struct is block-scoped, and the ICC color profile data is associated with the encoder and is managed separately.
=> fix: Remove attempt to free animated WebP ICC color profile data.

avcodec.go, giflib.go, lilliput.go, opencv.go, webp.cpp, webp.go, webp.hpp
This PR adds support for preserving the loop count when transforming animated WebP images.
The changes include:
- Adding a LoopCount() method to the Decoder interface.
- Implementing the LoopCount() method for various decoders.
- Modifying the WebP encoder to accept and use the loop count when creating animated WebP images.
- Updating the C++ code to handle loop count in both decoding and encoding processes.
These changes ensure that when transforming an animated WebP image, the original loop count is preserved in the output, maintaining the intended animation behavior.
=> fix: Preserve loop-count when transforming animated WebP input.

opencv.cpp, opencv.go, opencv.hpp, ops.go
This PR addresses an issue with the handling of background colors in animated WebP processing. Previously, the background color specified in the WebP file was being applied as an opaque color, which could lead to unexpected results, particularly for WebPs with transparent backgrounds. The [WebP specification](https://developers.google.com/speed/webp/docs/riff_container#animation) states the background color may be considered optional during decoding, which this PR does.
1. Replaced `FillWithColor` with `ClearToTransparent` in the initial setup of animated frame buffers.
2. Updated the `applyDisposeMethod` to use `ClearToTransparent` instead of `FillWithColor` when disposing to background color.
3. Modified the C++ code to implement a `clear_to_transparent` function, replacing the previous …
=> fix: Use transparent background with animated WebP outputs.

ops.go
Extension of https://github.com/discord/lilliput/pull/187 to also correct the dispose order for `resize` too.
=> fix: Correct the dispose order for resize operation too.

.github/workflows/deps.yaml, deps/verify_deps.py
Builds on #196 to create a checksum manifest of compiled native code deps, verify their integrity, and update the committed files in the `master` branch automatically when deps change.
=> Verify and auto-update native dependencies built in CI.

giflib.cpp, giflib.go, giflib.hpp
This PR enhances the GIF decoder to properly handle animated GIF to WebP conversion, focusing on frame disposal methods and animation metadata.
1. **Proper Frame Disposal**
- Maps GIF disposal methods to WebP equivalents
- Fixes visual artifacts in animations with transparent regions
- Properly handles frame-to-frame transitions
2. **Animation Metadata**
- Combined loop count and frame count reading into single pass
- Cached animation info to prevent redundant processing
- More accurate frame counting
3. **Performance**
- Single-pass metadata reading
- Cached animation information
- Reduced file parsing overhead
These changes ensure that animated GIFs are correctly converted to WebP format while maintaining visual fidelity and animation timing.
=> fix: Report frame-count, dispose-method, and background-color from GIF for use with animated WebP

giflib.cpp
Fixes: https://github.com/discord/lilliput/issues/84
I tried this with a number of different gifs, seems like it only happened with these stark black/white ones. In the specific case from the linked issue, white pixels from the witch silhouette were being incorrectly marked as transparent when they should remain opaque. The transparency is causing the previous frame's content to show through, creating the smearing effect.
| in | out |
| - | - |
|![in](https://github.com/user-attachments/assets/d8ff4d9f-d219-42cd-b09a-bb673f2b7732)|![out](https://github.com/user-attachments/assets/7af8c08c-7a5a-46bf-87cd-7898ea30ed32)|
So, we have a palette lookup table comprised of bit-crushed RGB values. For extreme colors like pure white (255,255,255), the crushed center calculation: `uint32_t R_center …
=> fix: "smearing" of gifs with transparent pixels

.github/workflows/ci.yaml, .github/workflows/deps.yaml, deps/build-deps-osx.sh, deps/osx/share/OpenCV/OpenCVModules.cmake
Support building the native codes dependencies on Mac OS X 15; previously this was limited to OS X 14. There were some minor changes required in the Lilliput build script for OS X. Also removes an unused CI stage meant to automatically check in compiled deps to the repo; this is not allowed for security reasons.
We'll continue to check in the dependencies compiled in Github CI for OS X 14. This change just ensures we can build for OS X 15 going forward, and makes an archive of OS X 15 compiled deps available for download through the Github CI build for anyone interested.
=> feat: Support compilation of native deps on OS X 15.

embed.go, go.mod
Basically by creating an embed go file, go recognizes the dependencies and downloads them along with the lilliput library code.
By using a build flag, that isn't actually called at build time, the embed.go file is not added so nothing is actually being embedded into the binary. 
This downloads the deps for both linux and mac (tested on m1 and linux containers). I wonder if we could be fancy with the OS and download only the OS specific ones but this was sufficient for my use-case
closes #195
=> Feature: embed required deps via a embed file that is behind a unused build flag

deps/build-deps-linux.sh, deps/build-deps-osx.sh
tag lilliput-deps-source with a new release, let's be a little bit safer around upgrades. using a shallow clone, since we dont need history of all deps, just the most recent one
=> misc: update build scripts to use release tag within lilliput-deps-source

.github/workflows/ci.yaml
Add some memory leak checks for lilliput
Testing memory leaks with valgrind, c++ and Go is a little hard but we can add basic checks in `definitely lost` and `indirectly lost` at least for the c++ code we call underneath.
We had a few regression in the past showing issues with these 2 and these checks while not extensive will already go a long way.
=> feat. Add valgrind on PR

.github/workflows/clang-format-check.yml, avcodec.cpp, avif.cpp, avif.hpp, giflib.cpp, opencv.cpp, opencv.hpp, thumbhash.cpp, webp.cpp, webp.hpp
Add a GitHub action triggered on push and PR to automatically run clang-format on cpp and hpp files at root only
Old state doesn't enforce clang-format but we provide a set of rules. This will ensure the code is always push according to these guidelines.
All cpp and hpp files modified here are the result of running clang-format
=> feat. add clang format GH action and run clang-format

deps/.gitignore, deps/build-deps-linux.sh, deps/build-deps-osx.sh, opencv.cpp
readHeader can throw an exception when using opencv, we don't want this to happen, instead we return false and output to std::cerr the error.
Fix build script to correctly cross-compile lcms
Add lcms deps directory to gitignore
=> misc. opencv safe readHeader call

deps/build-deps-linux.sh
Upgrading libpng to 1.6.47. The current one, 1.6.38, has an issue with opencv 4.11 and some large PNG files causing memory issues
=> misc. bump libpng

giflib.cpp
PR #244 added support for the "Restore Previous" GIF disposal method but also changed how unspecified disposal methods (0) were handled. Previously, `DISPOSAL_UNSPECIFIED` was treated as `GIF_DISPOSE_BACKGROUND` which cleared frames to background color, but it was changed to `GIF_DISPOSE_NONE` which caused frame compositing instead. Though this is compliant with the spec, it differs from the behavior assumed by many browsers.
This change restores the original behavior to maintain backward compatibility with existing GIFs that rely on the previous interpretation, fixing animation issues in Discord clients where frames were being incorrectly composited.
=> fix: Restore backward compatible handling of unspecified GIF disposal method.

giflib.cpp
This reverts commit 98065590f4eeb1e9354616abea972f760febfeae.
There's a different underlying issue that will be addressed in a separate PR.
=> Revert "fix: Restore backward compatible handling of unspecified GIF disposal method"

giflib.cpp
This PR addresses an issue where transparency information from GIF files was being discarded during the decoding process, resulting in incorrect background and transparency color values in GIF-to-GIF conversions.
- Removed the default initialization of `TransparentColor = NO_TRANSPARENT_COLOR` in the `giflib_get_frame_gcb` function
- This allows the original transparency color index from the source GIF to be preserved when reading GraphicsControlBlock information
- Added safeguards against removing transparency when background has partial transparency
- Restores use of No Dispose for case where disposal method is unspecified
- Background colors and transparency values are now correctly preserved in round-trip GIF-to-GIF conversions
- Maintains transparency information as specified in the …
=> fix: Preserve GIF transparent color across frames

avcodec.cpp, avcodec.go, avcodec.hpp, avif.go, examples/main.go, giflib.go, lilliput.go, opencv.go, webp.go
Expose specific codec information for video files instead of just container format. Video codecs supported: H264, HEVC, AV1, VP8, VP9, MPEG4 Audio codecs supported: AAC, MP3, FLAC, Vorbis, Opus Returns "Unknown" for unsupported codecs.
- Add VideoCodec() and AudioCodec() methods to Decoder interface
- Implement codec detection in avCodecDecoder using FFmpeg codec IDs
- Add codec methods to all decoder implementations for interface compatibility
- Update example to display codec information
- AVIF reports AV1 video codec, WebP reports VP8 video codec
=> feat: Add video and audio codec metadata reporting

deps/build-deps-osx.sh
Bumping the following osx versions to match linux:
zlib - accel
libpng - 1.6.47
giflib - 5.2.2
libyuv - libyuv-eb6e7bb63738e29efd82ea3cf2a115238a89fa51-2024-12-12
I would like to attempt to help with the png cicp issues for HDR PNG files, bumping libpng to match linux would enable the usage of `png_get_cICP` for both linux and osx builds
=> bump zlib, libpng, giflib, libyuv for osx to match linux
